#!/usr/bin/env bash
# This file:
#
#  - Publish a feature / release / hotfix branch.
#
# Usage:
#
#  LOG_LEVEL=7 ./ci-publish feature/01


# shellcheck source=lib/common-variables
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common-variables"


### Parse commandline options
##############################################################################

# Commandline options. This defines the usage page, and is used to parse cli
# opts & defaults from. The parsing is unforgiving so be precise in your syntax
# - A short option must be preset for every long option; but every short option
#   need not have a long option
# - `--` is respected as the separator between options and arguments
# - We do not bash-expand defaults, so setting '~/app' as a default will not resolve to ${HOME}.
#   you can use bash variables to work around this (so use ${HOME} instead)

# shellcheck disable=SC2015
read -r -d '' __usage <<- EOF || true # exits non-zero when EOF encountered
  -t --title    [title] The pull request title.
  -b --body     [body]  The pull request body.
  -h --help             This page.
  
  [branch]              The target branch to publish. Defaults to the current branch.
                        - For ${BRANCH_NAME_FEATURE}/* branches, pull request onto ${BRANCH_NAME_DEVELOP}. 
                        - For ${BRANCH_NAME_RELEASE}/* branches, pull request onto ${BRANCH_NAME_DEVELOP} and ${BRANCH_NAME_MASTER}. 
                        - For ${BRANCH_NAME_HOTFIX}/* branches, pull request onto ${BRANCH_NAME_DEVELOP} and ${BRANCH_NAME_MASTER}. 
EOF

# shellcheck disable=SC2015
read -r -d '' __helptext <<- EOF || true # exits non-zero when EOF encountered
 This script publishes a supporting branch (${BRANCH_NAME_FEATURE} / ${BRANCH_NAME_RELEASE} / ${BRANCH_NAME_HOTFIX})
 by creating a pull request that bases onto the corresponding main branch (${BRANCH_NAME_MASTER} / ${BRANCH_NAME_DEVELOP}).
EOF

# shellcheck source=lib/ci-common
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/ci-common"


### Runtime
##############################################################################

setup

__branch_name="${arg_branch:-${__starting_branch}}"

if [[ ${__branch_name} != ${BRANCH_NAME_FEATURE}/* && ${__branch_name} != ${BRANCH_NAME_RELEASE}/* && 
      ${__branch_name} != ${BRANCH_NAME_HOTFIX}/* ]]; then
  error "Branch \"${__branch_name}\" cannot be published."
  exit 1
fi

if ! is_branch_existing "${__branch_name}"; then
  error "Branch \"${__branch_name}\" does not exist."
  exit 1
fi

__target_branches=()
if [[ ${__branch_name} = ${BRANCH_NAME_FEATURE}/* ]]; then
  __target_branches=("${BRANCH_NAME_DEVELOP}")
elif [[ ${__branch_name} = ${BRANCH_NAME_RELEASE}/* ]]; then
  __target_branches=("${BRANCH_NAME_DEVELOP}" "${BRANCH_NAME_MASTER}")
elif [[ ${__branch_name} = ${BRANCH_NAME_HOTFIX}/* ]]; then
  __target_branches=("${BRANCH_NAME_DEVELOP}" "${BRANCH_NAME_MASTER}")
fi

info "Sync branch \"${__branch_name}\"."
exec_with_info git checkout "${__branch_name}"
exec_with_info git pull --ff-only "${REMOTE_ORIGIN}" "${__branch_name}"
exec_with_info git push "${REMOTE_ORIGIN}" "${__branch_name}"

__created_pr=
for __target_branch in "${__target_branches[@]}"; do
  info "Sync branch \"${__target_branch}\"."
  exec_with_info git checkout "${__target_branch}"
  exec_with_info git pull --ff-only "${REMOTE_ORIGIN}" "${__target_branch}"
  
  __pull_request_args="--base ${__target_branch}"
  if [[ -n "${arg_t}" || -n "${arg_b}" ]]; then
    if [[ -n "${arg_t}" ]]; then
      __pull_request_args="${__pull_request_args} --title '${__message//\'/\\\'}'"
    fi
    if [[ -n "${arg_b}" ]]; then
      __pull_request_args="${__pull_request_args} --body '${__message//\'/\\\'}'"
    fi
  else 
    __pull_request_args="${__pull_request_args:-} --fill"
  fi
  if git merge-base --is-ancestor "${__branch_name}" "${__target_branch}"; then
    notice "There are no commits between branch \"${__branch_name}\" and \"${__target_branch}\"." \
           "Pull request creation is skipped."
    continue
  fi
  __created_pr=1
  info "Create pull requests from branch \"${__branch_name}\" onto \"${__target_branch}\"."
  exec_with_info git checkout "${__branch_name}"
  exec_with_info gh pr create "${__pull_request_args}"
done

if [[ -z "${__created_pr:-}" ]]; then
  error "No pull requests are created. Is this expected?"
  exit 2
fi
