version: "3.8"

# This is the deployment config for production environment.
# This environment is composed of all the services fully functional, with ports published which is exactly needed
# by the business.
# 1. ALL the services should be deployed with at least "deploy.replicas: 1"
# 2. Specify the "image" of ALL the services EXCEPT for fundamental infrastructural services (e.g. dbs)
# 3. Customize the services' command arguments for production
# 4. Publish the ports of the services. Only the ports that are needed by outside business systems should be published. 
# 5. Configure label "environment=production" for all the services
# 6. Configure placement constraints by "deploy.placement.constraints" so that the services can only run on 
#    production-specific nodes
# 7. Restrain memory resources for EVERY service by "deploy.placement.resources.limits.memory"


services:
