#!/usr/bin/env bash

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Exit on error inside any functions or subshells.
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail
# Turn on traces, useful while debugging but commented out by default
# set -o xtrace

### Variable Definition
##############################################################################
JENKINS_DOCKER_VERSION="20.10.2"


### Runtime
##############################################################################

if [[ ! -f "docker-${JENKINS_DOCKER_VERSION}.tgz" ]]; then
    curl \
      -L "https://download.docker.com/linux/static/stable/x86_64/docker-${JENKINS_DOCKER_VERSION}.tgz" \
      -o "docker-${JENKINS_DOCKER_VERSION}.tgz"
fi

tar -zxvf "docker-${JENKINS_DOCKER_VERSION}.tgz"
