version: "3.8"

#x-deploy:
#  docker_compose_only: true

services:
  jenkins:
    image: ${DOCKER_NAMESPACE}/jenkins:0.1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role==manager
#          - node.labels.service==jenkins
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  jenkins:


volumes:
  jenkins:
