version: "3.8"


services:
  jenkins:
    image: localhost:5000/jenkins:0.1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        window: 10s
#      placement:
#        constraints:
#          - node.labels.service==logging
    ports:
      - 40000:8080
      - 50000:50000
    networks:
      - jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}:/usr/bin/docker


networks:
  jenkins:


volumes:
  jenkins:
